name: pusher_dart
description: Unofficial pusher client for dart
version: 0.2.0
homepage: https://github.com/jaysson/pusher_dart

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  web_socket_channel: ^2.2.0
  http: ^0.13.5
  meta: 1.7.0
